"""Workflow: merge five holes into one cut-out while keeping the curves that separate them.

The reliable way in every parametric CAD tool is at sketch level: turn the separating arcs into
construction (reference) geometry so they survive, trim the arcs that fall inside neighbouring
holes so the five circles become one outline, then re-cut that outline. In Blender (mesh), the
equivalent is dissolving the webs between the holes and keeping their boundary edges marked.
"""

RECOGNIZE = {
    "query": "each circular hole cut into the part (one box per hole)",
    "expected_count": 5,
    "say": "I can see the {n} holes. Let's merge them into one opening and keep the arcs between them as reference curves.",
}

FUSION_STEPS = [
    {
        "id": "edit_sketch",
        "title": "Edit the sketch",
        "say": "First, open the sketch that contains the holes. In the browser on the left, expand Sketches, right-click the holes sketch, and choose Edit Sketch.",
        "instruction": "Browser (left panel) ▸ expand “Sketches” ▸ right-click the sketch with the holes ▸ “Edit Sketch”. The toolbar switches to the SKETCH tab and a “FINISH SKETCH” button appears on the right.",
        "target": {"kind": "ui_text", "text": "Sketches", "alt": ["SKETCHES", "Sketch1", "Sketch"], "region": "left"},
        "expect": [{"kind": "ocr_contains", "text": "FINISH SKETCH"}, {"kind": "ocr_contains", "text": "SKETCH PALETTE"}],
        "timeout": 90,
        "alt": "You can also double-click the sketch icon under the part in the timeline at the bottom of the window.",
    },
    {
        "id": "construction",
        "title": "Keep the separating arcs",
        "say": "Now protect the curves between the holes. Click each arc where two holes meet, hold Control to pick several, then press X. They turn into dashed construction lines and stay as reference.",
        "instruction": "Click each arc that separates two neighbouring holes (Ctrl+click to add), then press X (Normal/Construction). Dashed arcs = kept as reference curves.",
        "target": {"kind": "geometry", "query": "the short arcs where neighbouring holes meet or overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Are there dashed (construction) arcs drawn between the holes in the sketch?"}, {"kind": "manual"}],
        "timeout": 120,
        "optional": True,
        "alt": "If clicking the arcs is fiddly, draw the separating arcs again with Create ▸ Arc ▸ 3-Point Arc and press X on each new arc.",
    },
    {
        "id": "trim_tool",
        "title": "Pick the Trim tool",
        "say": "Press T on the keyboard, or open Modify and choose Trim. The Trim dialog appears.",
        "instruction": "Press T  (or Sketch toolbar ▸ MODIFY ▸ Trim). A small “TRIM” dialog opens.",
        "target": {"kind": "ui_text", "text": "MODIFY", "alt": ["Modify"], "region": "top", "key": "T"},
        "expect": [{"kind": "ocr_contains", "text": "TRIM"}],
        "timeout": 60,
        "alt": "Right-click on empty canvas, choose Sketch ▸ Trim from the marking menu.",
    },
    {
        "id": "trim",
        "title": "Trim the inner arcs",
        "say": "Hover an arc that lies inside a neighbouring hole. It turns red. Click to remove it. Repeat for every inner arc until the five circles form one continuous outline.",
        "instruction": "Hover each arc segment that lies inside another hole (highlights red) and click to delete it. Go around all five holes. Result: one closed outline; the dashed arcs stay.",
        "target": {"kind": "geometry", "query": "arc segments of the circles that fall inside a neighbouring circle where the holes overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Do the five holes now form a single continuous outline with no solid arcs crossing inside the merged shape (dashed construction arcs are fine)?"}, {"kind": "manual"}],
        "timeout": 240,
        "alt": "Zoom in with the scroll wheel so each inner arc is easy to hit; you can undo a wrong trim with Ctrl+Z.",
    },
    {
        "id": "finish_sketch",
        "title": "Finish the sketch",
        "say": "Click Finish Sketch at the right end of the toolbar.",
        "instruction": "Click “FINISH SKETCH” (right end of the toolbar) or press Escape twice.",
        "target": {"kind": "ui_text", "text": "FINISH SKETCH", "alt": ["FINISH"], "region": "top"},
        "expect": [{"kind": "ocr_absent", "text": "FINISH SKETCH"}],
        "timeout": 60,
    },
    {
        "id": "cut",
        "title": "Cut the merged opening",
        "say": "Press E for Extrude, click inside the merged outline, set Operation to Cut and Extent to All, then click OK.",
        "instruction": "Press E ▸ click inside the merged profile ▸ in the EXTRUDE dialog set Operation = Cut, Extent = All (or the original hole depth) ▸ OK.",
        "target": {"kind": "ui_text", "text": "CREATE", "alt": ["Create"], "region": "top", "key": "E"},
        "expect": [{"kind": "vision", "question": "Has the merged five-hole opening been cut into the solid part (one connected opening visible in the 3D body)?"}, {"kind": "manual"}],
        "timeout": 180,
        "alt": "If the old holes still exist as a separate feature, right-click that feature in the timeline and choose Suppress so only the merged cut remains.",
    },
]

ONSHAPE_STEPS = [
    {
        "id": "edit_sketch",
        "title": "Edit the sketch",
        "say": "Open the sketch with the holes: in the Feature list on the left, double-click it.",
        "instruction": "Feature list (left) ▸ double-click the sketch that holds the holes. The sketch toolbar and a Sketch dialog with a green check appear.",
        "target": {"kind": "ui_text", "text": "Sketch 1", "alt": ["Sketch", "Features"], "region": "left"},
        "expect": [{"kind": "ocr_contains", "text": "Sketch"}, {"kind": "vision", "question": "Is a sketch open for editing (sketch toolbar with line/circle/trim tools visible)?"}],
        "timeout": 90,
    },
    {
        "id": "construction",
        "title": "Keep the separating arcs",
        "say": "Select each arc between two holes, holding Control for several, and press Q to make them construction geometry. They become dashed and are kept.",
        "instruction": "Click each arc separating two holes (Ctrl+click to add) ▸ press Q (Construction). Dashed arcs = kept.",
        "target": {"kind": "geometry", "query": "the short arcs where neighbouring holes meet or overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Are there dashed (construction) arcs between the holes?"}, {"kind": "manual"}],
        "optional": True,
        "timeout": 120,
    },
    {
        "id": "trim_tool",
        "title": "Pick the Trim tool",
        "say": "Click Trim in the sketch toolbar. It's the scissors icon.",
        "instruction": "Sketch toolbar ▸ “Trim” (scissors icon).",
        "target": {"kind": "ui_text", "text": "Trim", "alt": ["TRIM"], "region": "top"},
        "expect": [{"kind": "vision", "question": "Is the Trim sketch tool active (Trim button highlighted or trim cursor)?"}, {"kind": "manual"}],
        "timeout": 60,
    },
    {
        "id": "trim",
        "title": "Trim the inner arcs",
        "say": "Click every arc that lies inside a neighbouring hole. Each click removes one segment. Stop when the five circles form one outline.",
        "instruction": "Click each arc segment inside another hole to remove it, around all five holes, until one closed outline remains.",
        "target": {"kind": "geometry", "query": "arc segments of the circles that fall inside a neighbouring circle where the holes overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Do the five holes now form a single continuous outline with no solid arcs inside the merged shape?"}, {"kind": "manual"}],
        "timeout": 240,
    },
    {
        "id": "finish_sketch",
        "title": "Accept the sketch",
        "say": "Click the green check in the Sketch dialog.",
        "instruction": "Click the green ✓ in the Sketch dialog (top-left of the graphics area).",
        "target": {"kind": "window_region", "rel": [0.02, 0.08, 0.22, 0.14]},
        "expect": [{"kind": "vision", "question": "Has the sketch been closed (no sketch dialog with a green check visible)?"}, {"kind": "manual"}],
        "timeout": 60,
    },
    {
        "id": "cut",
        "title": "Remove the merged opening",
        "say": "Click Extrude, select the merged region, choose Remove and Through all, then accept.",
        "instruction": "Toolbar ▸ Extrude ▸ click inside the merged profile ▸ Remove ▸ End type “Through all” ▸ green ✓.",
        "target": {"kind": "ui_text", "text": "Extrude", "alt": ["EXTRUDE"], "region": "top"},
        "expect": [{"kind": "vision", "question": "Has one connected opening been cut through the part where the five holes were?"}, {"kind": "manual"}],
        "timeout": 180,
    },
]

SOLIDWORKS_STEPS = [
    {
        "id": "edit_sketch",
        "title": "Edit the sketch",
        "say": "In the FeatureManager tree on the left, expand the cut feature, right-click its sketch and choose Edit Sketch.",
        "instruction": "FeatureManager (left) ▸ expand the Cut-Extrude feature ▸ right-click its sketch ▸ “Edit Sketch”.",
        "target": {"kind": "ui_text", "text": "Cut-Extrude", "alt": ["Sketch", "Cut"], "region": "left"},
        "expect": [{"kind": "ocr_contains", "text": "Exit Sketch"}, {"kind": "ocr_contains", "text": "Trim Entities"}],
        "timeout": 90,
    },
    {
        "id": "construction",
        "title": "Keep the separating arcs",
        "say": "Select each arc between two holes, then in the PropertyManager tick For construction. They become dashed reference curves.",
        "instruction": "Click each separating arc (Ctrl+click for several) ▸ PropertyManager ▸ tick “For construction”.",
        "target": {"kind": "geometry", "query": "the short arcs where neighbouring holes meet or overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Are there dashed (construction) arcs between the holes?"}, {"kind": "manual"}],
        "optional": True,
        "timeout": 120,
    },
    {
        "id": "trim_tool",
        "title": "Pick Trim Entities",
        "say": "On the Sketch tab click Trim Entities, and choose Power trim.",
        "instruction": "Sketch tab ▸ “Trim Entities” ▸ Power trim.",
        "target": {"kind": "ui_text", "text": "Trim Entities", "alt": ["Trim"], "region": "top"},
        "expect": [{"kind": "ocr_contains", "text": "Power trim"}, {"kind": "ocr_contains", "text": "Trim"}],
        "timeout": 60,
    },
    {
        "id": "trim",
        "title": "Trim the inner arcs",
        "say": "Hold the mouse button and drag across each arc that lies inside a neighbouring hole. Release when the five circles form one outline.",
        "instruction": "Drag the cursor across each inner arc (Power trim removes what you cross) until one closed outline remains.",
        "target": {"kind": "geometry", "query": "arc segments of the circles that fall inside a neighbouring circle where the holes overlap", "multi": True},
        "expect": [{"kind": "vision", "question": "Do the five holes now form a single continuous outline with no solid arcs inside the merged shape?"}, {"kind": "manual"}],
        "timeout": 240,
    },
    {
        "id": "finish_sketch",
        "title": "Exit the sketch",
        "say": "Click Exit Sketch in the top-right corner of the graphics area.",
        "instruction": "Click “Exit Sketch” (confirmation corner, top-right) or the green check.",
        "target": {"kind": "ui_text", "text": "Exit Sketch", "alt": ["Exit"], "region": "top"},
        "expect": [{"kind": "ocr_absent", "text": "Exit Sketch"}],
        "timeout": 60,
    },
    {
        "id": "cut",
        "title": "Rebuild the cut",
        "say": "The Cut-Extrude feature updates on its own. If it shows an error, edit it, choose Through All, and click OK.",
        "instruction": "Features tab ▸ Extruded Cut (if the existing cut errored: right-click it ▸ Edit Feature ▸ Through All ▸ OK).",
        "target": {"kind": "ui_text", "text": "Extruded Cut", "alt": ["Features"], "region": "top"},
        "expect": [{"kind": "vision", "question": "Has one connected opening been cut through the part where the five holes were?"}, {"kind": "manual"}],
        "timeout": 180,
    },
]

BLENDER_STEPS = [
    {
        "id": "edit_mode",
        "title": "Enter Edit Mode",
        "say": "With the part selected, press Tab to enter Edit Mode, then press 3 for face select.",
        "instruction": "Select the object ▸ Tab (Edit Mode) ▸ 3 (Face select).",
        "target": {"kind": "ui_text", "text": "Object Mode", "alt": ["Edit Mode"], "region": "top", "key": "Tab"},
        "expect": [{"kind": "ocr_contains", "text": "Edit Mode"}],
        "timeout": 60,
    },
    {
        "id": "mark_separators",
        "title": "Mark the separating edges",
        "say": "Alt-click the rim of each hole to select its boundary loop, then press Control E and choose Mark Sharp. Those curves are kept.",
        "instruction": "Alt+click each hole rim (Shift+Alt+click to add) ▸ Ctrl+E ▸ “Mark Sharp” (they turn cyan and survive the merge).",
        "target": {"kind": "geometry", "query": "the rims of the circular holes", "multi": True},
        "expect": [{"kind": "vision", "question": "Are the hole rims highlighted as sharp (cyan) edges?"}, {"kind": "manual"}],
        "optional": True,
        "timeout": 120,
    },
    {
        "id": "select_webs",
        "title": "Select the webs between holes",
        "say": "Click the thin wall faces that separate neighbouring holes, holding Shift to add them.",
        "instruction": "Shift+click every thin wall face between two holes (top and bottom faces of each web).",
        "target": {"kind": "geometry", "query": "the thin walls between neighbouring holes", "multi": True},
        "expect": [{"kind": "vision", "question": "Are the thin wall faces between the holes selected (highlighted orange)?"}, {"kind": "manual"}],
        "timeout": 180,
    },
    {
        "id": "dissolve",
        "title": "Remove the webs",
        "say": "Press X and choose Faces. The holes join into one opening.",
        "instruction": "X ▸ “Faces”. Then Alt+click the new opening rim and press F if any gap needs filling.",
        "target": {"kind": "key", "keys": "X"},
        "expect": [{"kind": "vision", "question": "Do the holes now form one connected opening in the mesh?"}, {"kind": "manual"}],
        "timeout": 120,
    },
]

FREECAD_STEPS = [
    {
        "id": "edit_sketch",
        "title": "Edit the holes sketch",
        "say": "First, open the sketch that holds the five holes. In the Model tree on the left, expand Body, then double-click HolesSketch. The Sketcher opens and a Tasks panel with a Close button appears.",
        "instruction": "Model tree (left) ▸ expand “Body” ▸ double-click “HolesSketch” (under the Holes pocket). While the sketch is open the Tasks panel shows “Solver messages” and a “Close” button.",
        "target": {"kind": "ui_text", "text": "HolesSketch", "alt": ["Sketch", "Holes", "Body"], "region": "left"},
        "expect": [{"kind": "ocr_contains", "text": "Solver messages"}, {"kind": "ocr_contains", "text": "Edit controls"}],
        "timeout": 90,
        "alt": "Right-click the sketch in the Model tree and choose Edit sketch, or use the Sketch menu ▸ Edit sketch.",
    },
    {
        "id": "bridge",
        "title": "Draw the bridging rectangle",
        "say": "Now bridge the holes. Press G then R for the rectangle tool. Click a little above the centre of the leftmost hole, then a little below the centre of the rightmost hole. Keep the rectangle narrower than the holes so their outer curves stay.",
        "instruction": "Press G, R (Rectangle) ▸ click point ① just above the centre of the leftmost hole ▸ click point ② just below the centre of the rightmost hole. The rectangle must be shorter than the hole diameter so every hole keeps its top and bottom arc.",
        "target": {"kind": "hole_points", "pattern": "bridge", "key": "G, R"},
        "expect": [{"kind": "vision", "question": "Is there a rectangle drawn across the row of circles, passing through their centres, in the sketch?"}, {"kind": "manual"}],
        "timeout": 150,
        "alt": "You can also draw two horizontal lines (G, L) from the first hole to the last, one above and one below the centres, and join their ends with short vertical lines.",
    },
    {
        "id": "trim_tool",
        "title": "Pick Trim edge",
        "say": "Press G then T to pick the Trim edge tool. The status bar says Trim edge.",
        "instruction": "Press G, T (Sketch ▸ Sketcher tools ▸ Trim edge). The status bar at the bottom reads “Trim edge”.",
        "target": {"kind": "window_region", "rel": [0.25, 0.06, 0.75, 0.16], "key": "G, T"},
        "expect": [{"kind": "ocr_contains", "text": "Trim edge"}, {"kind": "ocr_contains", "text": "Trim"}],
        "timeout": 60,
        "optional": True,
        "alt": "Sketch menu ▸ Sketcher tools ▸ Trim edge.",
    },
    {
        "id": "trim",
        "title": "Trim inside the merged shape",
        "say": "Click every segment that lies inside the merged shape: the arcs of each circle that fall inside the rectangle, and the rectangle edges that fall inside a circle. The outer arcs of the holes stay, so the merged opening keeps its curves. Stop when one closed outline remains.",
        "instruction": "With Trim edge active, click: each circle arc inside the rectangle (the sides facing a neighbour), each piece of the rectangle's top and bottom edge inside a circle, and the two short vertical ends. Leave the outer arcs of every hole: they are the curves between the holes. Finish with one closed outline.",
        "target": {"kind": "hole_points", "pattern": "inner", "key": "G, T"},
        "expect": [{"kind": "vision", "question": "In the sketch, do the five circles and the rectangle now form a single continuous closed outline (a scalloped slot) with no line or arc segments left inside it?"}, {"kind": "manual"}],
        "timeout": 300,
        "alt": "Zoom in with the mouse wheel to hit each segment; Ctrl+Z undoes a wrong trim. If Solver messages reports an error, undo the last trim.",
    },
    {
        "id": "close",
        "title": "Close the sketch",
        "say": "Click Close at the top of the Tasks panel. The Holes pocket recomputes into one opening.",
        "instruction": "Tasks panel (left) ▸ “Close”. The Holes pocket recomputes: one scalloped opening instead of five holes.",
        "target": {"kind": "ui_text", "text": "Close", "alt": ["Solver messages"], "region": "left"},
        "expect": [{"kind": "ocr_absent", "text": "Solver messages"}],
        "timeout": 60,
        "alt": "Press Escape with nothing selected, or Sketch ▸ Leave sketch.",
    },
    {
        "id": "confirm",
        "title": "Check the merged opening",
        "say": "Look at the part: the five holes should now be one opening with curved sides. If the pocket shows an error mark in the tree, open the sketch again and remove any leftover segment inside the outline.",
        "instruction": "The 3D view shows one connected opening. If “Holes” carries a red mark in the tree, reopen HolesSketch and trim the leftover segment.",
        "target": {"kind": "hole_points", "pattern": "all"},
        "expect": [{"kind": "vision", "question": "Does the plate show one connected opening (a scalloped slot) where the five separate holes were?"}, {"kind": "manual"}],
        "timeout": 120,
    },
]

MERGE_HOLES = {
    "id": "merge_holes",
    "name": "Merge five holes, keep the separating curves",
    "keywords": [["merg", "join", "combin", "connect", "unite", "fuse"], ["hole", "circle", "opening", "cutout", "cut-out"]],
    "recognize": RECOGNIZE,
    "apps": {
        "fusion360": {"label": "Fusion 360", "match": {"process": ["fusion360.exe"], "title": ["fusion 360", "autodesk fusion"]}, "steps": FUSION_STEPS},
        "onshape": {"label": "Onshape", "match": {"title": ["onshape"]}, "steps": ONSHAPE_STEPS},
        "solidworks": {"label": "SolidWorks", "match": {"process": ["sldworks.exe"], "title": ["solidworks"]}, "steps": SOLIDWORKS_STEPS},
        "blender": {"label": "Blender", "match": {"process": ["blender.exe"], "title": ["blender"]}, "steps": BLENDER_STEPS},
        "freecad": {"label": "FreeCAD", "match": {"process": ["freecad.exe"], "title": ["freecad"]}, "steps": FREECAD_STEPS},
    },
    "default_app": "fusion360",
    "done_say": "That's the merge done: one opening, with the separating arcs kept as reference curves. Nice work.",
}
